### ISSUE TITLE
Running Nextflow workflow with TESK fails

### ISSUE THREAD

**Issue by shukapoo** [CINECA-project/wp4-federated-joint-cohort-analysis#2] opened 2020-03-11 11:47 UTC
In Nextflow, the endpoint is specified using environment variables:
export NXF_MODE=ga4gh
export NXF_EXECUTOR=tes
export NXF_EXECUTOR_TES_ENDPOINT='https://csc-tesk.c03.k8s-popup.csc.fi/'

We followed the instruction from here:
https://www.nextflow.io/docs/latest/executor.html#ga4gh-tes

The section from the log is not very informative, but it seems that it tries to use a local working directory on my computer:
Jan-28 16:16:25.800 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jan-28 16:16:25.873 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jan-28 16:16:25.873 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'tes'
Jan-28 16:16:25.879 [main] DEBUG n.ga4gh.tes.executor.TesExecutor - [TES] endpoint=https://csc-tesk.c03.k8s-popup.csc.fi/
Jan-28 16:16:25.879 [main] DEBUG nextflow.executor.Executor - [warm up] executor > tes [https://csc-tesk.c03.k8s-popup.csc.fi/]
Jan-28 16:16:25.887 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'tes' > capacity: 100; pollInterval: 1s; dumpInterval: 5m
Jan-28 16:16:25.950 [main] DEBUG n.ga4gh.tes.executor.TesExecutor - [TES] endpoint=https://csc-tesk.c03.k8s-popup.csc.fi/
Jan-28 16:16:26.063 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > say_hello -- maxForks: 4
Jan-28 16:16:26.116 [main] DEBUG nextflow.script.BaseScript - No entry workflow defined
Jan-28 16:16:26.117 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Jan-28 16:16:26.117 [main] DEBUG nextflow.Session - Session await
Jan-28 16:16:26.190 [Actor Thread 3] DEBUG n.ga4gh.tes.executor.TesExecutor - [TES] Launching process > say_hello -- work folder: /Users/alasoo/work/3c/eb038d6fc516b779fe2348a9724e6d
Jan-28 16:16:26.858 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'say_hello'

However, if I mis-specify the endpoint (e.g. https://csc-tesk.c03.k8s-popup.csc.ee/) then I get a different error, which suggests that it is able to recognise that it's at least a valid URL:
Jan-28 16:20:13.915 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'say_hello'

Caused by:
  csc-tesk.c03.k8s-popup.csc.ee: nodename nor servname provided, or not known

**Comment by tskir** [comment] 2020-04-28 10:08
All right. Since the error message is not informative, I've cloned the Nextflow core repository and [built it from source](https://github.com/nextflow-io/nextflow#build-from-source).

The first problem is that when [ApiException](https://github.com/nextflow-io/nextflow/blob/415ac310c92ab14be7f1dbefea5534d8c97ff648/modules/nf-ga4gh/src/main/nextflow/ga4gh/tes/client/ApiException.java#L51) is called with (message, throwable, code, responseHeaders, responseBody), it only logs the message (which turns out to be empty in this case) and the casual exception (of which there is none), and ignores response code, headers, and body. So this explains the uninformative message.

**Comment by tskir** [comment] 2020-04-28 10:11
I then located all cases where `ApiException` is thrown in the TES support module. There are 12 such cases.

The `ApiException` which we see is thrown in the case where response status is not OK (not 2xx), but the HTTP response itself is nevertheless well formed. By directly modifying the exception thrown, I was able to extract the **response** returned by TESK:

```json
{
  "timestamp" : "2020-04-28T10:01:41.826+0000",
  "status" : 401,
  "error" : "unauthorized",
  "message" : "The request was rejected because the URL was not normalized.",
  "path" : "//v1/tasks",
  "error_description" : "Full authentication is required to access this resource"
}
```

@shukapoo Perhaps this alone might tell you what could be the problem. I'm currently working on extracting the request body as well, will let you know once it's done.

**Comment by shukapoo** [comment] 2020-04-28 10:40
Thanks @tskir, JWT based OIDC Authentication was turned on for `https://csc-tesk.c03.k8s-popup.csc.fi/` TESK endpoint last week.

Above error seems to be due to `unauthorized access`. 

Please use `https://csc-tesk-test.rahtiapp.fi/swagger-ui.html` TESK endpoint, it has OIDC Authentication Switched off.

**Comment by tskir** [comment] 2020-04-28 12:13
@shukapoo Thanks! When retried with the new endpoint, the error is:

```json
{
  "timestamp" : "2020-04-28T12:11:49.242+0000",
  "status" : 500,
  "error" : "Internal Server Error",
  "message" : "The request was rejected because the URL was not normalized.",
  "path" : "//v1/tasks"
}
```

So not very informative as well. I'll get back to you when I'm able to extract the request which is being performed as well.

**Comment by tskir** [comment] 2020-04-28 12:28
@shukapoo OK, I think I'm getting somewhere. So far I can see **two** unrelated problems:

## Permissions on csc-tesk-test.rahtiapp.fi
When I try to manually GET https://csc-tesk-test.rahtiapp.fi/v1/tasks, it returns:
```json
{
  "timestamp" : "2020-04-28T12:21:30.751+0000",
  "status" : 500,
  "error" : "Internal Server Error",
  "message" : "Forbidden",
  "path" : "/v1/tasks"
}
```

I don't think it should be the case, should it? The same happens if I try to execute an example "POST /v1/tasks" commands in the swagger UI.

## URL normalisation
In all tests so far, run both by you and me, we used the endpoint name with the trailing slash. The Nextflow code appends '/v1/tasks' to the endpoint name, and the result is https://csc-tesk-test.rahtiapp.fi//v1/tasks with two slashes. Apparently TESK isn't happy about it and complains because the “URL was not normalized”, before even starting to process it.

When I specify the endpoint without the trailing slash, I get a more meaningful error message:
```json
{
  "timestamp" : "2020-04-28T12:19:42.479+0000",
  "status" : 400,
  "error" : "Bad Request",
  "path" : "/v1/tasks",
  "messages" : [ "Field 'inputs[1].type' must not be null", "Field 'outputs[2].type' must not be null", "Field 'outputs[3].type' must not be null", "Field 'outputs[0].type' must not be null", "Field 'executors[0].image' must not be blank", "Field 'inputs[0].type' must not be null", "Field 'outputs[1].type' must not be null" ]
}
```

I'm still working on extracting the original request which is being submitted by Nextflow to TESK. However, before that I think we should fix the issue with the 500 returned by GET https://csc-tesk-test.rahtiapp.fi/v1/tasks.

**Comment by shukapoo** [comment] 2020-04-28 12:58
That's strange @tskir, I am able to create & view tasks without any authentication.
```skapoor@skapoor-air13:.ssh$ curl -X GET "https://csc-tesk-test.rahtiapp.fi/v1/tasks?view=MINIMAL" -H "accept: application/json"
{
  "tasks" : [ {
    "id" : "task-30255807",
    "state" : "RUNNING"
  }, {
    "id" : "task-4cf39f44",
    "state" : "RUNNING"
  }, {
    "id" : "task-51ddc179",
    "state" : "RUNNING"
  }, {
    "id" : "task-7cf1d609",
    "state" : "RUNNING"
  }, {
    "id" : "task-b313d67b",
    "state" : "RUNNING"
  }, {
    "id" : "task-f7c85fbe",
    "state" : "RUNNING"
  } ]
}

skapoor@skapoor-air13:.ssh$ curl -X POST "https://csc-tesk-test.rahtiapp.fi/v1/tasks" -H "accept: application/json" -H "ContentType: application/json" -d "{ \"description\": \"An example presenting: Inputs, Outputs, Resources, Stdout, Workdir\", \"executors\": [ { \"command\": [ \"sh\", \"-c\", \"cat ./input ; echo Hello $SECRET_PROJECT_NAME\" ], \"env\": { \"SECRET_PROJECT_NAME\": \"TESK\" }, \"image\": \"alpine\", \"stderr\": \"/tes/err\", \"stdout\": \"/tes/output\", \"workdir\": \"/tes\" } ], \"inputs\": [ { \"description\": \"Downloading a single file from HTTP\", \"name\": \"File from HTTP\", \"path\": \"/tes/input\", \"type\": \"FILE\", \"url\": \"https://raw.githubusercontent.com/EMBL-EBI-TSI/TESK/master/examples/success/hello.json\" } ], \"name\": \"hello tesk\", \"outputs\": [ { \"description\": \"Example of uploading a directory to FTP\", \"name\": \"Dir to FTP\", \"path\": \"/tes\", \"type\": \"DIRECTORY\", \"url\": \"ftp://ftp-private.ebi.ac.uk/upload/examples/tes\" } ], \"resources\": { \"cpu_cores\": 1, \"disk_gb\": 0.1, \"ram_gb\": 2 }, \"tags\": { \"Version\": \"5.15\" }, \"volumes\": [ \"/tes/temp\" ]}"
{
  "id" : "task-ae038cf9"
}

**Comment by tskir** [comment] 2020-04-28 13:10
@shukapoo Now it works for me too! Did you do anything to fix it?

The response when launched via Nextflow remains the same, so it doesn't appear to be related and is really a problem with how Nextflow forms TES requests. I'll continue to investigate.

**Comment by lvarin** [comment] 2020-04-28 13:22
Hello,

There was an internal problem with the service account that submits the job. 

By default the template that configure the application, tries to give fine grain permissions to the service account, but Rahti does not allow it. So I had to give more permissions manually to that account.

Regards

**Comment by lvarin** [comment] 2020-04-28 13:27
```
2020-04-28 12:32:08.099 TRACE 1 --- [nio-8080-exec-7] u.a.e.t.t.u.c.KubernetesClientWrapper    : ApiException ResponseBody: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","messa
ge":"jobs.batch is forbidden: User \"system:serviceaccount:csc-tesk-test:taskmaster\" cannot create jobs.batch in the namespace \"csc-tesk-test\": no RBAC policy matched","reason":"Forbidden","detai
ls":{"group":"batch","kind":"jobs"},"code":403}
```

**Comment by tskir** [comment] 2020-04-29 16:38
## Body of the Nextflow → TESK requests

I was able to extract the body of the request Nextflow sends to TESK. Well, this is not the actual JSON which is being submitted, but its Java's internal `.toString()` representation. But it still provides all of the info which we need:

```
TesTask {
    id: null
    state: null
    name: null
    description: null
    inputs: [class TesInput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.command.sh
        path: /work/.command.sh
        type: null
        content: null
    }, class TesInput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.command.run
        path: /work/.command.run
        type: null
        content: null
    }]
    outputs: [class TesOutput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.command.out
        path: /work/.command.out
        type: null
    }, class TesOutput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.command.err
        path: /work/.command.err
        type: null
    }, class TesOutput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.command.log
        path: /work/.command.log
        type: null
    }, class TesOutput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.exitcode
        path: /work/.exitcode
        type: null
    }]
    resources: class TesResources {
        cpuCores: 1
        preemptible: null
        ramGb: 0.0
        diskGb: null
        zones: null
    }
    executors: [class TesExecutor {
        image: null
        command: [/bin/bash, -c, /bin/bash -uex .command.run &> .command.log]
        workdir: /work
        stdin: null
        stdout: null
        stderr: null
        env: null
    }]
    volumes: null
    tags: null
    logs: null
    creationTime: null
}
```

**Comment by tskir** [comment] 2020-04-29 16:53
## Fixing the problem with `null` input/output types

As you can see, it submits all jobs with two predefined inputs (actual script to run & internal Nextflow wrapper script) and four predefined outputs (out, err, log and return code).

The problem is that the `type` parameter of all inputs is always `null`, for example:
```
class TesOutput {
        name: null
        description: null
        url: /home/ktsukanov/repositories/nextflow/work/70/4b9d6842d1e3bff0285a9a46982f42/.exitcode
        path: /work/.exitcode
        type: null
    }
```

TES schema allows this parameter to be missing, but if it's present, it [has to be](https://github.com/ga4gh/task-execution-schemas/blob/9cc12b0c215a7f54fdeb0d0598ebc74fa70eb2a7/openapi/task_execution.swagger.yaml#L261) either `FILE` or `DIRECTORY`.

This problem can be fixed by modifying Nextflow code and specifying the type as `FILE` explicitly.

**Comment by tskir** [comment] 2020-04-29 17:04
## Fixing the problem with `null` executor image

TES [requires](https://github.com/ga4gh/task-execution-schemas/blob/9cc12b0c215a7f54fdeb0d0598ebc74fa70eb2a7/openapi/task_execution.swagger.yaml#L217) executor's image to be explicitly specified. To do that, Nextflow needs to be run with the `-with-docker ${IMAGE_NAME}` flag, for example `-with-docker alpine`.

This can be fixed by updating Nextflow documentation to include this important detail.

**Comment by tskir** [comment] 2020-04-30 13:51
@shukapoo, @kauralasoo, @lvarin: I'm glad to report that this particular ticket is finally resolved. I have introduced the necessary changes into Nextflow code and verified that they resolve the problem with a failing request.

I have opened a pull request in Nextflow repository: https://github.com/nextflow-io/nextflow/pull/1589.

I have updated the instructions to run Nextflow and opened a pull request in _our_ repository: https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/pull/12.

Finally, I have created a number of follow up tickets:
* https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/issues/13 — Provide access to a test Kubernetes pod for further Nextflow/TESK testing
* https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/issues/14 — Tasks submitted to csc-tesk-test.rahtiapp.fi appear to run forever

With that, I'm closing this issue.

**Closed as completed** 2020-04-30 13:51 UTC
